### ISSUE TITLE
i file splittati contengono 'tmp-' e non vengono trovati

### ISSUE THREAD

**Issue by pigreco** [ondata/30cappa#13]
https://github.com/ondata/30cappa/blob/6320bd92fb373df41efd79c91209732ecf47fd62/script/arigadicomando/dataETL.sh#L65

**Comment by aborruso** [comment]
Ciao @pigreco non riesco a riprodurre l'errore.

Quando io lancio

```
mapshaper "$folder"/../../dati/arigadicomando/tmp.shp -split PRO_COM_T -o format=geojson "$folder"/../../dati/arigadicomando/output_noreg/
```

Il file `tmp.shp`, creato poco sopra fa da input e vengono creati i 5000 JSON di output in `dati/arigadicomando/output_noreg`

Dovresti farmi vedere non tanto il comando dello script, ma l'errore

**Comment by pigreco** [comment]
@aborruso 
intanto ho modificato i percorsi per non scrivere nelle cartelle del repo.

poi, lo script genera questi file:
![image](https://user-images.githubusercontent.com/7631137/103167759-2ae0c080-482e-11eb-9bb6-1503748c57f5.png)

e successivamente, ultima riga dello script, cerca i file a partire dal file `lista.tsv` che contiene :
![image](https://user-images.githubusercontent.com/7631137/103167859-181abb80-482f-11eb-8b6e-a7509749933c.png)

uso mapshaper 0.4.142

**Comment by aborruso** [comment]
@pigreco usi una versione molto vecchia. 

Devi aggiornare mapshaper. Grazie a questa issue ho aggiornato i requisiti
