### ISSUE TITLE
Cambiare fonte dati popolazione: da ISTAT a ANPR

### ISSUE THREAD

**Issue by aborruso** [ondata/30cappa#14]
La fonte primaria di dati sulla popolazione è ANPR.

I dati ISTAT sono aggiornati a 1 anno fa, mentre quelli ANPR dovrebbero essere aggiornati continuamente.

Fonti ANPR possibili sono:

- https://www.anpr.interno.it/portale/documents/20182/241820/Comuni+subentrati.xlsx
- https://dashboard.anpr.it/api/dashboard/data.json

**Comment by pigreco** [comment]
> I dati ISTAT sono aggiornati a 1 anno fa, mentre quelli ANPR dovrebbero essere aggiornati continuamente.

In effetti con i dati ISTAT nell'intervallo tra 4500 e 5500 abitanti ci sono circa 400 comuni.

**Comment by napo** [comment]
facciamo un test con ANPR?

**Comment by aborruso** [comment]
Nella colonna check anpr-istat del primo figlio, ho messo il valore alert per circa 25 righe da attenzionare.

In rosso i comuni che non sono più sotto 5001 (circa  24) e in verde quelli che lo sono (1).

https://docs.google.com/spreadsheets/d/1BAqLOAO9bXXSQLOCkkDeLj7PGeX6UzxPBKroIXIXde4/edit#gid=0

**Comment by aborruso** [comment]
Questa chiudiamola. Purtroppo non ci sono "certezze"
